repos:
#  - repo: https://github.com/psf/black
#    rev: 25.9.0
#    hooks:
#      - id: black
#        language_version: python3
#        args: ["--line-length=88"]

#  - repo: https://github.com/pycqa/flake8
#    rev: 7.3.0
#    hooks:
#      - id: flake8
#        args:
#          - --max-line-length=88
#          - --exclude=.venv